SRC/ShineWiFi-ModBus/Config.h.example
SRC/ShineWiFi-ModBus/ShineWiFi-ModBus.ino

Added WifiManager, reconnect improvements, MQTT Server, username and password config via WifiManager

Added WifiManager and MQTT configuration

---

SRC/ShineWiFi-ModBus/Config.h.example
SRC/ShineWiFi-ModBus/Growatt.cpp
SRC/ShineWiFi-ModBus/ShineWiFi-ModBus.ino

1. If the USB-Stick is not Connected to an Inverter the Device Type could not be Set. So i've added a check for that case.
2. At the JSON-Output, there i've added the MacAddress of the Device. This could be used by the Victron Venus OS as Serial

Inverter simulate

---

SRC/ShineWiFi-ModBus/Config.h.example
SRC/ShineWiFi-ModBus/Growatt.cpp
SRC/ShineWiFi-ModBus/Growatt.h
SRC/ShineWiFi-ModBus/ShineWiFi-ModBus.ino
SRC/ShineWiFi-ModBus/index.h

Instead of using checkboxes user can now select _register type_, _operation_ and _register size_ from dropdown menu. It is possible to read 16b and 32b registers which makes it much easier to figure out what modbus protocol the inverter uses.

'RW modbus' page improvement

---

SRC/ShineWiFi-ModBus/Config.h.example
SRC/ShineWiFi-ModBus/ShineWiFi-ModBus.ino

// Timer definitions:
//    REFRESH_TIMER: Modbus polling rate [ms]
//    RETRY_TIMER: Determines the time between reconnection [ms]
//    LED_TIMER: Led blinking rate [ms]
//    BUTTON_TIMER: enter config mode after 5*BUTTON_TIMER [ms]

Make all timers configurable from config.h

---

README.md
SRC/ShineWiFi-ModBus/ShineWiFi-ModBus.ino

Moved the setup instructions to main readme to make it more visible for new users.

Readme updates

---

SRC/ShineWiFi-ModBus/Growatt.cpp

Signed-off-by: crasu <spam@crasu.de>

fix case for missing Config.h error message

---

SRC/ShineWiFi-ModBus/ShineMqtt.h
SRC/ShineWiFi-ModBus/WebDebug.c
SRC/ShineWiFi-ModBus/WebDebug.h

Simple compilation fix for #64 and #63.
* Made sure it compiles with and without webdebug enabled. 
* Flashed the fix

Fix compilation error with WEBDEBUG enabled

---

README.md
SRC/ShineWiFi-ModBus/Config.h.example
SRC/ShineWiFi-ModBus/ShineMqtt.cpp
SRC/ShineWiFi-ModBus/ShineMqtt.h
SRC/ShineWiFi-ModBus/ShineWiFi-ModBus.ino
SRC/ShineWiFi-ModBus/ShineWifi.h
SRC/ShineWiFi-ModBus/WebDebug.cpp
SRC/ShineWiFi-ModBus/WebDebug.h

* Fix compiling bugs https://github.com/otti/Growatt_ShineWiFi-S/issues/64, compiling when mqtt is of. 
* Update Comments
* Add more ifdefs to disable functions completely

fix comp bugs; feat more ifdef for post processing; add some comments

---

SRC/ShineWiFi-ModBus/Config.h.example
SRC/ShineWiFi-ModBus/ShineWiFi-ModBus.ino

fix missing ifdef if http updater is disabled

---

SRC/ShineWiFi-ModBus/ShineMqtt.cpp
SRC/ShineWiFi-ModBus/ShineMqtt.h
SRC/ShineWiFi-ModBus/ShineWiFi-ModBus.ino

- Creates a class similar to the Growatt class we use for protocol handling
- Flashed to esp32 webinterface works
- Connection to inverter is untested

Moved mqtt handling to its own class

---

README.md

Split readme and add homeassistant config

---

SRC/ShineWiFi-ModBus/Config.h.example

Seems to cause issues with stick detection
closes #94

Disable debug output 

---

CHANGELOG.md
README.md
SRC/ShineWiFi-ModBus/Config.h.example
SRC/ShineWiFi-ModBus/ShineMqtt.h
SRC/ShineWiFi-ModBus/ShineWiFi-ModBus.ino
SRC/ShineWiFi-ModBus/ShineWifi.h

Adds mqtts for the esp32 only
* Compiles
* Can be flashed
* Tested on inverter

Esp32 mqtts support

---

SRC/ShineWiFi-ModBus/Index.h
SRC/ShineWiFi-ModBus/ShineWiFi-ModBus.ino

* add uistatus link and back link for RW Modbus
* move RW Modbus html to index.h
* add html-body around Modbus-form

add links & html-body

---

.gitignore
SRC/ShineWiFi-ModBus/Growatt.cpp
SRC/ShineWiFi-ModBus/Index.h

* added status interpretation as unit
* added ° in front of C
* renamed DataCointainer to DataContainer
* uses half space between number and unit

Added status interpretation

---

README.md

The config did not work with version 1.0.0's MQTT messages, topic was not correct and some quotation marks had to be adjusted. Running this config successfully

Updated HA MQTT Config

---

README.md

... and add (my) supported inverter.

fix desciption to the doc

---

SRC/ShineWiFi-ModBus/Config.h.example
SRC/ShineWiFi-ModBus/ShineWiFi-ModBus.ino
platformio.ini

- Tested on esp8266 nodemcu and lolin32 with simulated inverter

Replaced AP_BUTTON_PRESSED in Config.h

---

platformio.ini

Build All really Build All configurations.

Build All really Build All configurations

---

SRC/ShineWiFi-ModBus/ShineWiFi-ModBus.ino

https://github.com/otti/Growatt_ShineWiFi-S/issues/148
not tested, yet.

increase password length

---

SRC/ShineWiFi-ModBus/Growatt.cpp
platformio.ini

My Inverter-Data (and my SmartMeter-Data)  does not fit in the JSON array.
Increasing solve this. I see no really downsides on this.
Tested with
* MOD 6k
* MID 30k
* (Victron ET340)

increase JSONSize

---

.github/workflows/dco.yaml

This check enforce every commit to be signed of with the -s git option. Commit to this repo with the signoff options means that your code has been commited under MIT License.
https://git-scm.com/docs/git-commit#Documentation/git-commit.txt---signoff

Add dco check

---

SRC/ShineWiFi-ModBus/Index.h

First of all, great work thank you ! 
I see that you are using highchart, this is not under MIT license and so far not open source.
I like Chart.js this is under MIT license and opensource to.
I change the website (because iam using the website quite often), you can check it out on jsfiddle.
you can check how it looks like here :  [jsfiddle](https://jsfiddle.net/x3n027/buds8k0y/286/)
tested on ESP8266 and Growatt shine S Stick.
here is a screenshot how it looks like: 
can someone else test it ?

change from highcharts to chart.js with MIT license

---

SRC/ShineWiFi-ModBus/Config.h.example
platformio.ini

Tested on esp32 with a simulated inverter.
Signed-off-by: crasu <spam@crasu.de>

fix compilation issue on windows

---

README.md
SRC/ShineWiFi-ModBus/Config.h.example
SRC/ShineWiFi-ModBus/Growatt.cpp
SRC/ShineWiFi-ModBus/ShineMqtt.cpp
SRC/ShineWiFi-ModBus/ShineMqtt.h
SRC/ShineWiFi-ModBus/ShineWiFi-ModBus.ino
platformio.ini

See https://github.com/otti/Growatt_ShineWiFi-S/pull/143

Teelog (corrected)

---

.github/workflows/platformio.yaml
platformio.ini

adding ENV for d1 mini without AP-Button
also add building Firmware and move to firmware_d1
now with Sign off  
all complete and clean in one request

Adding bare D1 mini without AP-Button

---

README.md

After figuring out earlier how to send and receive responses to MQTT commands in Home Assistant I thought it would be good to document them in the README to provide examples for others trying to achieve similar results.
I have also moved the other code blocks into ``` style blocks with syntax highlighting.

Document MQTT commands

---

SRC/ShineWiFi-ModBus/Config.h.example
SRC/ShineWiFi-ModBus/Growatt.cpp
SRC/ShineWiFi-ModBus/GrowattTypes.h
SRC/ShineWiFi-ModBus/Index.h
SRC/ShineWiFi-ModBus/ShineMqtt.cpp
SRC/ShineWiFi-ModBus/ShineWiFi-ModBus.ino
platformio.ini

Updates via http are supported by wifi manager… already. Added menu item to wifi manager for updates via config wlan.
Tested on simulated inverter on esp32/esp8266.

Removed http updater and updated wifi manager to latest version

---

SRC/ShineWiFi-ModBus/Growatt.cpp
SRC/ShineWiFi-ModBus/Growatt.h
SRC/ShineWiFi-ModBus/Growatt120.cpp
SRC/ShineWiFi-ModBus/Growatt124.cpp
SRC/ShineWiFi-ModBus/Growatt305.cpp
SRC/ShineWiFi-ModBus/GrowattSPF.cpp
SRC/ShineWiFi-ModBus/GrowattTypes.h

tested with simulated inverter

Convert field name strings to flash helper

---

SRC/ShineWiFi-ModBus/ShineWiFi-ModBus.ino
SRC/ShineWiFi-ModBus/ShineWifi.cpp
SRC/ShineWiFi-ModBus/ShineWifi.h

Disconnect wifi after config ap start

---

SRC/ShineWiFi-ModBus/Config.h.example
SRC/ShineWiFi-ModBus/Growatt124.cpp

Workaround for different multiplier on same sph inverter firmware version

---

SRC/ShineWiFi-ModBus/Growatt.cpp
SRC/ShineWiFi-ModBus/Growatt.h
SRC/ShineWiFi-ModBus/Growatt124.cpp
SRC/ShineWiFi-ModBus/ShineMqtt.cpp
SRC/ShineWiFi-ModBus/ShineMqtt.h

Tested on esp32 with simulated inverter when invoking the battery first get command.

Fix buffer size issue when sending out mqtt command reponses

---

Doc/MQTT.md
Doc/ShineWiFi-S/ShineWiFi-S.md

Added more detailed description form closed issues and personal experience, that helped me and might save time for others.

Update ShineWiFi-S.md with more details and recent changes of the circuit

---

SRC/ShineWiFi-ModBus/ShineMqtt.cpp

Tested on simulated inverter with lolin32

Fix request response mixup

---

Doc/Prometheus.md
README.md

This pull request adds a documentation file detailing the Prometheus format, following up on #320.

Add documentation for Prometheus

---

SRC/ShineWiFi-ModBus/Growatt.cpp

Signed-off-by: crasu <spam@crasu.de>

Fix uint compiler warning

---

Doc/MQTT.md
README.md
SRC/ShineWiFi-ModBus/Growatt124.cpp
SRC/ShineWiFi-ModBus/Growatt124.h

Follow-up on https://github.com/OpenInverterGateway/OpenInverterGateway/pull/271#issuecomment-2132258178 and https://github.com/OpenInverterGateway/OpenInverterGateway/pull/271#issuecomment-2159245177

Growatt124, added power limiting functionallity

---

SRC/ShineWiFi-ModBus/ShineWiFi-ModBus.ino

ArduinoOTA silently calls MDNS.begin which results to unexpected behavior including crashes if
MDNS.begin is called twice during setup.
Furthermore MDNS.Update has to be called in loop() on ESP8266 if ArduinoOTA is not enabled.
ArduinoOTA.begin() has to be moved up before Log.begin because TLog silenty calls MDNS.addService which
will lead to the next crash if MDNS.begin() has not been called before.
While at it move the ArduinoOTA.handle() out of the REFRESH_TIMER condition where it was
incorrectly placed. Also error out if no OTA_PASSWORD was defined, but OTA_SUPPORT was enabled.

fix: MDNS and OTA issues

---

SRC/ShineWiFi-ModBus/ShineWiFi-ModBus.ino

this adds the possibility to configure a syslog server through wifimanager.

feat: add support for syslog server

---

SRC/ShineWiFi-ModBus/GrowattTLXH.cpp

this allows to set the inverter priority mode by means of a timeslot that spaws the whole day. Please make sure that no other priority timeslots are set otherwise this will not work correctly (holding registers 3038-3045, 3050-3059 must be 0).

feat(GrowattTLXH): add call to set priority mode

---

platformio.ini

Please include a summary of the change and which issue is fixed.

Use fixed version for tee log. 
