OpenInverterGateway/OpenInverterGateway

SRC/ShineWiFi-S_ModBus.ino
An error was printed when a USB shine stick was detected in the web debug mode
=> Print out correct stick type in web debug mode when using USB

.github/workflows/platformio.yaml, SRC/ShineWiFi-ModBus/Config.h.example, SRC/ShineWiFi-ModBus/Growatt.cpp, SRC/ShineWiFi-ModBus/Growatt.h, SRC/ShineWiFi-ModBus/ShineWiFi-ModBus.ino, platformio.ini
* Makes it possible to build this project on esp32 boards (lolin32). 
* Add support for double reset as the lolin only has a reset button
* Make it possible too manually trigger the gh action workflow
* Automatic handling of mqtt ids
* Now rebased to master
* Installs on ESP8266 and ESP32
* Wifi&Website do load
* mqtt connection works
* Connection to inverter and reporting works with lolin32
* Connection to inverter is untested with esp8266
=> Add esp32 support

SRC/ShineWiFi-ModBus/Config.h.example
compilation in ArduinoIDE was not working because the MQTT_MAX_PACKET_SIZE was only defined in platformio.ini.
=> define MQTT_MAX_PACKET_SIZE in config.h

SRC/ShineWiFi-ModBus/Growatt124.cpp
Fixes #52 
The input register value 49 _"Three phase grid output power (low)"_ was missing from the read fragment.
Now the value is returned correctly:
```json
"L1ThreePhaseGridVoltage": 235.5,
"L1ThreePhaseGridOutputCurrent": 0.7,
"L1ThreePhaseGridOutputPower": 164.8,
"L2ThreePhaseGridVoltage": 234.4,
"L2ThreePhaseGridOutputCurrent": 0.7,
"L2ThreePhaseGridOutputPower": 164,
"L3ThreePhaseGridVoltage": 233.7,
"L3ThreePhaseGridOutputCurrent": 0.7,
"L3ThreePhaseGridOutputPower": 163.5,
```
=> Fix missing L3ThreePhaseGridOutputPower value

SRC/ShineWiFi-ModBus/ShineMqtt.cpp
Client ID sometimes contained special characters which made the mqtt connection fail on some devices.
Fixes #90
=> Fix client id generation

SRC/ShineWiFi-ModBus/Config.h.example, SRC/ShineWiFi-ModBus/Growatt.cpp, SRC/ShineWiFi-ModBus/GrowattSPF.cpp, SRC/ShineWiFi-ModBus/GrowattSPF.h
I disassembled ShineWifi-F stick, which is used for Growatt SPF5000ES, and also turned out similar
to other ShineWifi (ESP8266 inside), difference
with Serial one is that RS232 are send over data
lines of USB.
Another problem of Growatt is totally different protocol, thankfully available as PDF in internet.
Code tested on Growatt SPF5000ES + custom adapter
(based on Wemos D1 + MAX3232 + USB connector).
Signed-off-by: Denys Fedoryshchenko <denys.f@collabora.com>
=> Add SPF3500/5000 Modbus protocol support.

SRC/ShineWiFi-ModBus/Growatt.cpp, SRC/ShineWiFi-ModBus/Growatt.h, SRC/ShineWiFi-ModBus/GrowattTypes.h, SRC/ShineWiFi-ModBus/ShineWiFi-ModBus.ino
As SPF protocol shows, battery balance are shown as "signed" value, e.g. if we have value -1000 it means battery being charged, if it is 1000 it means battery is discharged.
(Holding register 77, 32-bit value, SPF5000 Modbus protocol) Tested only on 32-bit input register.
Signed-off-by: Denys Fedoryshchenko <denys.f@collabora.com>
=> Add support for "signed" registers

SRC/ShineWiFi-ModBus/Growatt.cpp, SRC/ShineWiFi-ModBus/Growatt.h, SRC/ShineWiFi-ModBus/Growatt120.cpp, SRC/ShineWiFi-ModBus/Growatt124.cpp, SRC/ShineWiFi-ModBus/Growatt305.cpp, SRC/ShineWiFi-ModBus/GrowattSPF.cpp, SRC/ShineWiFi-ModBus/GrowattTypes.h
Hey Hoh,
this Pull requests extends the device tables with a resolution. This resolution is then used to round the Values. Before that, it was always rounded by two digits behind the dot.
Hope it helps.
sincerely
=> Rounding by resolution

SRC/ShineWiFi-ModBus/ShineMqtt.cpp
I think this is a bug noone can see because it's only visible when debugging is off.
=> Fix return statement

platformio.ini
Disables the buildwarning for line 41-45 in Config.h(.example).
=> disable Comment Warning for multiline comments

SRC/ShineWiFi-ModBus/Growatt124.cpp
Hi Again,
I am checking the Values and the Temperature of my Battery pack was not showing in the right scale.
The Problem is that the Datasheet shows that the Temperature has a scale of 0.1, but this is not right (check screenshots) it musst be 1.0.
I change it and test it on my SPH4600 with Growatt ARK LV Battery pack.
ID1040 (Battery Temperature)
That the Battery temperature is 1.8° is not possible due the actual Temperature ;)
I also read out ID1089 which is the actual BMS Temperature (same result ->18)
Regards
=> change battery temperature scale

SRC/ShineWiFi-ModBus/Growatt.cpp
add cast to double. So our floating points have decimal places again (within jsons).
=> Fix missing floating point

SRC/ShineWiFi-ModBus/Growatt124.cpp, SRC/ShineWiFi-ModBus/Growatt124.h, SRC/ShineWiFi-ModBus/Growatt305.cpp
Adds two new properties to the v124 spec
- `ACChargeEnergyToday` based on input register 1124, described as "AC Charge Energy Today H" / "Energy today" in spec
- `ACChargeEnergyTotal` based on input register 1126, described as "AC Charge Energy Total H" / "Energy total" in spec
These match up with the `eacharge_today` and `eacharge_total` values from the original firmware.
I've also fixed a typo in a few places `FEAGMENT` -> `FRAGMENT`.
I wasn't sure if I should make a new fragment or increase the range of the existing fragment 3, but figured it would be safest to make a new one. I am also not sure if I needed to put the size of the fragment as 2 or 3 so went with 3 just in case. Happy to modify these if there is a better way.
=> Add v124 AC charging properties

.github/workflows/platformio.yaml, platformio.ini
This adds a new environment to the platformio.ini file for the Shine WiFi-S monitor.
I have also added the esp8266 exception decoder monitor, which will automatically decode exceptions when debugging.
I am using this the resulting build successfully on my Shine WiFi-S stick.
=> Add Shine WiFi-S environment to PlatformIO

SRC/ShineWiFi-ModBus/Growatt.cpp, SRC/ShineWiFi-ModBus/Growatt.h, SRC/ShineWiFi-ModBus/Growatt120.cpp, SRC/ShineWiFi-ModBus/Growatt120.h, SRC/ShineWiFi-ModBus/Growatt124.cpp, SRC/ShineWiFi-ModBus/Growatt124.h, SRC/ShineWiFi-ModBus/Growatt305.cpp, SRC/ShineWiFi-ModBus/Growatt305.h, SRC/ShineWiFi-ModBus/GrowattSPF.cpp, SRC/ShineWiFi-ModBus/GrowattSPF.h, SRC/ShineWiFi-ModBus/ShineMqtt.cpp, SRC/ShineWiFi-ModBus/ShineMqtt.h, SRC/ShineWiFi-ModBus/ShineWiFi-ModBus.ino
I've created a new MQTT command API which depending on your modbus version will allow you to perform specific actions against the inverter, particularly ones that would not normally be possible through the RW modbus page as e.g. they require writing multiple registers at the same time on the inverter firmware or it rejects the update.
Currently, you can retrieve and set the datetime on v1.24 inverters with a MQTT API. I later plan to add the ability to manage the schedules for e.g. charging off the grid at night time (#167) but wanted to get some early feedback with the general approach I've gone for here before continuing with that.
Note I'm not primarily a C++ / microcontroller developer and mostly work in more managed languages like C# so I apologise if I've made any silly mistakes …
=> Add MQTT API

SRC/ShineWiFi-ModBus/Growatt.cpp, SRC/ShineWiFi-ModBus/Growatt.h
As promised in my last PR #201 here is a MQTT version of the postCommunicationModbus HTTP API. I did not remove the original as I was not sure if you wanted to keep it for now or not, happy to add that to this PR as well if you want.
Examples:
-------
-------
=> Add modbus RW interface to MQTT commands

README.md, SRC/ShineWiFi-ModBus/Growatt124.cpp
This PR adds new commands for the v1.24 modbus version that allows the user to read and update the various battery and grid first settings, which allows them to e.g. charge their battery from the grid overnight. It is a 1:1 match of the 'Battery First' and 'Grid First' settings on the official Growatt server config page.
I was unable to get the 'Battery First1' and 'Grid First1' equivalents functional as the inverter responded very strangely to setting the values as documented so I have left them out, it is unlikely to have more than 3 schedules anyway.
I have also updated the `datetime/get` command to return the datetime in the `value` field instead of `message` to make it nicer, and updated the Home Assistant example in the README to match.
Fixes #167
Examples:
---------
Request: …
=> Add battery / grid first commands

SRC/ShineWiFi-ModBus/ShineWiFi-ModBus.ino
With this change, the page looks a tiny little bit nicer and has a link to click on instead of having to copy & paste or manually write the IP.
=> Output a link to the AP configuration page

SRC/ShineWiFi-ModBus/Growatt.cpp, SRC/ShineWiFi-ModBus/GrowattBP.cpp, SRC/ShineWiFi-ModBus/GrowattBP.h
This pull request expands OpenInverterGateway to include the capability of retrieving data from Growatt BP inverters. Additionally, it enables reading the battery status and the charging and discharging power of the APX storage.
https://www.dennis-parsch.de/blog/post/custom-firmware-auslesen-eines-growatt-mod-10ktl3-xh-bp-apx-speicher
=> feat: added support for growatt bp series

SRC/ShineWiFi-ModBus/ShineWiFi-ModBus.ino
This PR addresses the WiFi reconnection issue described in #298. If the pinger is unable to ping the gateway, then the ESP is restarted. I'm open to suggestions for a better approach.
I have been running this firmware for more than two months without any issues. On average, the device is restarted twice per day. I suspect this may also be related to the behavior of the access point.
=> Restart ESP on ping failure

SRC/ShineWiFi-ModBus/Growatt.cpp, SRC/ShineWiFi-ModBus/Growatt.h, SRC/ShineWiFi-ModBus/GrowattTypes.h, SRC/ShineWiFi-ModBus/ShineWiFi-ModBus.ino
This pull request adds a new `/metrics` endpoint that exposes the same data available from `/status` using the Prometheus exporter format instead of the JSON format. This feature is useful because it is now possible to scrape the metrics from a Prometheus server. All the metrics start with `growatt_` (i.e. `growatt_pv1_voltage`) and they have a `mac` label set to the MAC address of the device.
=> Add /metrics endpoint as Prometheus exporter

SRC/ShineWiFi-ModBus/Growatt.cpp, SRC/ShineWiFi-ModBus/Growatt.h
This pull request fixes an error for which the snake case conversion was not correctly handled for the metric `TemperatureInsideIPM`. The incorrect returned value was `growatt_temperature_insideipm`, while the correct value now is `growatt_temperature_inside_ipm`.
=> Fix error in snake_case conversion

.github/workflows/dco.yaml, .github/workflows/linter.yaml, .github/workflows/platformio.yaml
This fixes CI annotations:
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20:
actions/checkout@v3, actions/cache@v3, actions/setup-python@v4. For more information see:
https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
See commit message above.
=> Update used GitHub actions

SRC/ShineWiFi-ModBus/ShineWiFi-ModBus.ino
- An error message "Read [...] impossible" for writing errors was confusing.
- The messages used a mix of "Register" and "register". Use always "register".
- Replace "Holding" and "Input" by lowercase variants (see Growatt documentation).
See commit message above.
=> Fix wrong message for failure of MODBUS write and clean others

SRC/ShineWiFi-ModBus/ShineWiFi-ModBus.ino
we can disable mqtt be leaving the server address empty. In this case don't waste CPU cycles generating the json and try to connect. We also stop spoiling the log with not connected messages.
=> fix(mqtt): do not call sendMqttJson if mqtt is disabled

SRC/ShineWiFi-ModBus/Growatt.cpp
Current code does not handle signed registers correctly. The issue has been solved in getRegValue so simply use this code.
=> fix(UIJson): handle signed values correctly

SRC/ShineWiFi-ModBus/Growatt124.cpp, SRC/ShineWiFi-ModBus/Growatt124.h
This puts a label at the end of the eP124InputRegisters_t input registers to avoid manually counting the registers.
=> refactor(Growatt124): do not manually count input registers

SRC/ShineWiFi-ModBus/Growatt.cpp
We use a StaticJsonDocument for all our metrics at the moment. If we define too many metrics the json output will be silently trucated. Increasing the StaticJsonDocument size seems to be an issue at least on the 8266 platform. So print at least a warning for now.
=> feat(createJson): print a warning if the document overflowed

SRC/ShineWiFi-ModBus/Index.h
if we accidently click on that link we instantly loose connectivity to the esp.
=> feat(web): ask for confirmation before starting config AP

SRC/ShineWiFi-ModBus/Growatt.cpp
RegisterUnit_t defines one more item than unitStr.
=> fix(GrowattTypes): possible oob access in unitStr

SRC/ShineWiFi-ModBus/ShineWiFi-ModBus.ino
It turns out the the current sendMetrics implementation is terribly slow. This is most likely because StringStream.read() will return only one character. As StringStream is already able to copy data to WifiClient in chunks avoid the WriteBufferingClient and send the data directly from StringStream to WifiClient.
=> fix(sendMetrics): avoid copying from buffer to buffer

SRC/ShineWiFi-ModBus/ShineMqtt.h, SRC/ShineWiFi-ModBus/ShineWiFi-ModBus.ino
currently the return value of millis() is stored in signed long variables. This will cause a stop of any timers after approx. 25 days when the output of millis() will become negative.
With unsigned long the time difference calcualtion for the timers will also work correctly when the millis() return value spills over after approx. 49 days.
=> fix(mainloop): millis() returns unsigned long

SRC/ShineWiFi-ModBus/Config.h.example, SRC/ShineWiFi-ModBus/ShineWiFi-ModBus.ino
This enables OTA updates via espota. Especially during development it is handsome to be able to update the device with first having to switch to AP mode to update the firmware. Especially when the device is connected to a real inverter that is not in the same building.
=> feat: add option to enable OTA updates

SRC/ShineWiFi-ModBus/Index.h, SRC/ShineWiFi-ModBus/ShineWiFi-ModBus.ino
This adds support to reboot the ESP to bring it back to a clean state if something is not working properly.
=> feat(webUI): add option to reboot the esp

.gitignore, platformio.ini
Allow extending the PlatformIO configuration locally with a gitignored `platformio-local.ini`. Useful for OTA uploads for example.
```ini
[env]
upload_protocol = espota
upload_port = 1.2.3.4
upload_flags =
--auth=upload-password-set-in-OTA_PASSWORD
```
=> Support overriding PlatformIO config using platformio-local.ini

SRC/ShineWiFi-ModBus/Config.h.example
The modbus page gives everyone with access to the web interface full access to the inverter. This pr disables the modbus page by default. You should either use the modbus interface via tls or compile your own firmware if you know what you are doing and want to take the risk.
=> Disable modbus in the default firmware due to security issues

SRC/ShineWiFi-ModBus/Config.h.example, SRC/ShineWiFi-ModBus/Growatt.cpp, SRC/ShineWiFi-ModBus/Growatt.h, SRC/ShineWiFi-ModBus/ShineMqtt.cpp, SRC/ShineWiFi-ModBus/ShineMqtt.h, SRC/ShineWiFi-ModBus/ShineWiFi-ModBus.ino
This adds support for setting a custom hostname and static ip settings.
If more than one inverter is in the installation it is good to be able
to distinguish the different inverters by name.
For sensors it is a good practice to give static ip addresses to them
especially if they are polled.
=> feat: add hostname and static ip settings

SRC/ShineWiFi-ModBus/Growatt.cpp
This fixes the missing insertion of an underscore if the last character of the String is uppercase and the second last is lowercase.
E.g. TemperatureA was not correctly converted to temperature_a before.
=> fix(Growatt::camelCaseToSnakeCase): single uppercase at the of String

SRC/ShineWiFi-ModBus/Config.h.example, SRC/ShineWiFi-ModBus/ShineWiFi-ModBus.ino
This enables the integrated SNTP timesync mechanism of the ESP and uses this to keep the inverter datetime in sync.
Please refer to Config.h.example on how to set NTP server and timezone.
=> feat: add support to set inverter datetime via NTP

SRC/ShineWiFi-ModBus/Growatt.cpp
This adds uptime, wifi rssi and heap information to metrics.
=> feat(metrics): add uptime, wifi rssi and heap information

SRC/ShineWiFi-ModBus/ShineWiFi-ModBus.ino
If the ESP fails to reconnec within connect timeout it will fire up a config AP with SSID ESP_xxxxx.
=> fix(WiFi_Reconnect): do not invoke wm.autoConnect()

SRC/ShineWiFi-ModBus/Growatt.cpp, SRC/ShineWiFi-ModBus/Growatt.h
Fix remaining occasions where a String is used unaltered in a function and thus avoid duplication at function call.
=> refactor: convert remaing String to const String&

SRC/ShineWiFi-ModBus/ShineMqtt.cpp, SRC/ShineWiFi-ModBus/ShineMqtt.h, SRC/ShineWiFi-ModBus/ShineWiFi-ModBus.ino
The red led is used to indicate different error scenarious. Currently it is used for failed mqtt connection and failed mobdus readout. Each of these errors clear and set the led state individually which is not correct.
This patch changes the behavior to set it if any of the error cases is true and clears it only if all are false.
While at it also add the unknown shine wifi stick case as an error.
=> fix: handle state of red led correctly

SRC/ShineWiFi-ModBus/Growatt.cpp, platformio.ini
It turns out that a significant portion of modbus requests fails returning in 2000ms stalls of the ESP since the default timeout in the ModbusMaster library is hardcoded to 2000ms.
In fact I think that the timeouts are busy response messages which the ModbusMaster can't handle.
Since the ModbusMaster library has not been updated for 8 years with many PRs for adding a timeout setting change to a fork which basically is the original library plus the support for setting a timeout.
Since 115200 baud is more than 10x faster than 9600 baud its resonable to reduce the timeout from 2000ms to 250ms. In my tests the failure rate was not changed by this reduction.
=> fix(Modbus): reduce modbus timeout from 2000 to 250ms for 115200 baud

SRC/ShineWiFi-ModBus/Growatt.cpp, SRC/ShineWiFi-ModBus/Growatt.h, SRC/ShineWiFi-ModBus/ShineWiFi-ModBus.ino
This change improves the overall generate and transmit time for arround 100 metrics on
my ShineWifiX stick from approx. 80 ms to 50 ms.
The current implementation is slower for 3 reasons:
- StringStream is not able to reserve memory. Thus each concat will cause realloc which even might leed to heap fragmentation.
- The printf("%g") in Growatt::metricsAddValue seems to be an expensive operation.
- Sending slices from a StringStream to WifiClient involves copying data.
While at it also add support for sending a 503 error if the last modbus readout failed or has not yet taken places. This avoids
that zero or outdated data is imported to prometheus.
=> feat(sendMetrics): improve create and transfer speed

SRC/ShineWiFi-ModBus/ShineWiFi-ModBus.ino
Add support for sending a 503 error if the last modbus readout failed or has not yet taken places. This avoids
that zero or outdated data is exported.
=> feat(sendJsonSite): return 503 if modbus data is outdated or invalid

SRC/ShineWiFi-ModBus/ShineWiFi-ModBus.ino
ESP.restart() does not clear the outputs so red and green led might still be on.
=> fix(setup): clear red and green led

SRC/ShineWiFi-ModBus/Index.h
Advertise the existence of the /metrics endpoint also on the front page of the webUI.
=> feat(webUI): add metrics endpoint to the front page

SRC/ShineWiFi-ModBus/Growatt.cpp, SRC/ShineWiFi-ModBus/Growatt.h, SRC/ShineWiFi-ModBus/Index.h, SRC/ShineWiFi-ModBus/ShineWiFi-ModBus.ino
This adds support for accessing individual register values via http without the need to request the full json or metrics output and parse it.
For example the output power can be queried via:
http://IPAddress/value/OutputPower
I use it for accessing the inverter data from inside evcc for example which issues a new request for each value it wants to get.
=> feat: add /value endpoint

SRC/ShineWiFi-ModBus/ShineWiFi-ModBus.ino
This moves the WifiManager from global to setup() context. This on one side saves about 500 bytes of heap. On the other side it gives the possibility to enter the config AP also by holding the AP button on power up if for whatever reason the main loop has an issue.
=> refactor: remove WifiManager from global context

SRC/ShineWiFi-ModBus/GrowattTypes.h
this fixes 2 issues with json document overflows.
1) when adding the active power rate to the existing implementation 2048 bytes was no longer sufficient.
2) when adding TLXH support a conditional increase of the doc size to 4096 was missing in the PR.
Change to 4096 bytes json document size unconditionally to fix both issues.
=> fix: json document overflow

SRC/ShineWiFi-ModBus/ShineWiFi-ModBus.ino
the config variable force_ap was not read in loadConfig
=> fix: config ap start through web interface

SRC/ShineWiFi-ModBus/GrowattTLXH.cpp
if AC charing is enabled this value can become negative
=> fix(GrowattTLXH): RealOutputPercent can be negative

SRC/ShineWiFi-ModBus/ShineWiFi-ModBus.ino
i have seen various bug reports with logs that show that the stick tries to connect to an mqtt server that obviously does not exist because its the hardcoded default.
As connecting to an non-existing server will cause stalls, change the default to empty (no server).
=> refactor(ShineMqtt): leave mqtt server field blank per default

.github/workflows/platformio.yaml
This adds support for building a firmware for ShineWifiX with TLXH support
=> Update platformio.yaml for build of TLXH inverters

platformio.ini
Please include a summary of the change and which issue is fixed.
=> Fix disappeared modbus master repo #425

CHANGELOG.md, Doc/MQTT.md, Doc/ShineWiFi-S/ShineWiFi-S.md, Doc/ShineWiFi-X/ShineWiFi-X.md, SRC/ShineWiFi-ModBus/Config.h.example, SRC/ShineWiFi-ModBus/Growatt305.h
This pull requests addresses typos in the documentation and in code comments.
=> Improve documentation and fix some typos

SRC/ShineWiFi-ModBus/Growatt124.cpp
Add the missing linefeed to the following log message:
```
init_growatt124: input registers 54 holding registers 1
```
- Tested on my own stick by building new firmware, uploading it to the stick and controlling the log output.
=> Add missing LF in log message

SRC/ShineWiFi-ModBus/Index.h
The W3C validator (https://validator.w3.org/) reports two issues for the HTML code
which are fixed here.
=> Fix HTML issues reported by W3C validator

SRC/ShineWiFi-ModBus/Index.h
small gui changes but with big effect in my opinion. instead of links we use some css magic that is looks like buttons and the menu is more separated from content. i like simple gui's but sometimes a button is more clear than a pure link ;-) 
tested also with my father and it is now much clearer if i ask him to send me the logs ;-)
maybe I have met your style too.
- [ x ] Firefox
- [ x ] Chromium
- [ x ] Vivaldi
- [ x ] iPhone Safari
- [ x ] Inverter type e.g. Growatt MIC 600 TL-X
- [ x ] Shine X
- [ x ] Nodemcu v3
=> simple ButtonBar instead of pure web links for the menu
